const UPDATETODO ="UPDATETODO"
const UPDATEID ="UPDATEID"
const DELETEONE ="DELETEONE"
const ALLDELETE ="ALLDELETE"
const CHANGEDONE ="CHANGEDONE"
export{UPDATETODO,UPDATEID,DELETEONE,ALLDELETE,CHANGEDONE}